// change this everyday
export const FOLDER_PATH = "6_5_2023";

export const RENAME_PDFS = true;

export const CATEGORY_MAP = {
  FROZEN: [
    "Crabby Cakes",
    "Lobster Tails",
    "Lobster Bodies",
    "Lobster Meat CK",
    "Lobster Meat CK-B",
    "Tuna Saku",
    "Tuna Steak",
    "Sword Steak",
    "Mahi Fillet",
    "Mahi Portions",
    "Basa Fillet",
    "Scungilli",
    "Ocean Tide",
    "Blue Label",
    "Yacht",
    "Rock Shrimp",
    "Smoked salmon",
    "Crayfish Tail Meat",
    "Barramundi Fillet",
    "Baby whole Pulpo",
    "Pulpo COOKED tentacles",
    "pulpo",
    "Hamachi Fillet",
    "Squid Rings",
    "apple TT 5/8",
    // shrimps
    "shell on",
    "pd tail",
    "cooked",
  ],
  "SALMON ITEMS": [
    /SALMON \d+\/\d+?/i,
    "salmon12/14",
    "SALMON FILLET",
    "NZ KING SALMON",
    "KING SALMON",
  ],
  "OTHER WHOLE FISH": [
    /BLACK SEABASS(?: \d+\/\d+)?/i,
    "HAMACHI",
    "ICELANDIC STEAK COD",
    /MONK TAILS(?: \d+)?\+/i,
    "monk tails",
    /SNAPPER(?: \d+\/\d+)?/i,
    "HALIBUT",
    "SMOKED SABLE/BLACK COD",
    "black cod",
    /STEELHEAD(?: \d+\/\d+)?/i,
    "WILD STRIPED BASS",
    "chilean sea bass",
    "chilean seabass",
    "12/14 BONED TROUT",
    /trout boned(?: \d+\/\d+)?/i,
    "16/20 DRESSED TROUT",
    "OCEAN TROUT",
    "Pompano",
    "Arctic Char",
    "hake",
  ],
  "FRESH FILLETS": [
    "TROUT FILLET",
    "HAMACHI FILLET",
    /FLUKE FILLET(?: \d+\/\d+)?/i,
    /^HALIBUT FILLET.*/i,
    "ICELANDIC COD FILLET",
    "REFRESH COD FILLET",
    "TILAPIA FILLET 7/9",
    /TILAPIA FILLET(?: \d+\/\d+)?/i,
    /SUSHI FLUKE(?: \d+\/\d+)?/i,
    "HAKE FILLET",
  ],
  "LOBSTERS ORDERS/ CUSTOMER": [/lobsters? \d+(\.\d+)?/i, "lobster CULL/CHIX"],
  "LOINS /CUSTOMER": [
    "TUNA LOIN 1",
    "TUNA LOIN 1+",
    "TUNA LOIN 2+",
    "BLUEFIN TUNA LOIN",
    "SWORD LOIN",
  ],
  SCALLOPS: ["dry scallops U12", "dry scallops U10"],
  "SHELL FISH": [
    "Chowder",
    "CHOPPED CLAMS",
    "retail mussels",
    "BEYER MUSSELS",
    "CLAM STRIPS",
    "COCKLE CLAMS",
    "cockles",
    "MANILLA CLAMS",
    "CHERRY CLAMS",
    "VA LITTLE NECKS",
    "LOCAL LITTLE NECKS",
    "FL LITTLE NECKS",
    "FL LITTLE NECK",
    "TOP NECK CLAM",
    "STEAMER CLAM",
    "BONE MAINE MUSSELS",
    "PEI mussels",
    "MUSSELS - CAPE COD",
    "COCKLE CLAMS",
    "top neck",
  ],
  OYSTERS: [
    "BEAU SOLIEL",
    "PACIFIC OYSTER",
    "BLUE POINT",
    "MALEPQUE",
    "INDIAN CREEK",
    "WEST COAST OYSTER",
    "SWEET PETITE",
    "KUMAMOTO",
  ],
  "IMPORTED FISH": [
    "BRANZINI 4/6",
    "BRANZINI 6/8",
    "BRANZINI 8/10",
    "Dorado",
    "DOVER SOLE  5/6",
  ],
  "PAST. CRAB MEAT": [
    "COLOSSAL",
    "JUMBO LUMP",
    "BACK FINN /LUMP",
    "SPECIAL CRAB MEAT",
    "LIVE ROCK CRABS",
    "CLAW MEAT",
    "PEEKY TOE CRAB MEAT",
  ],
  "MISC ITEMS": [
    "TOBIKO ORANGE",
    "Salmon Roe",
    "FRESH SQUID REGULAR",
    "UNI",
    "SQUID INK",
    "SCALLOPS SHELLS",
    "HIYASHI WIKAME",
  ],
  "SOFT SHELL CRAB  (CUSTOMER)": [
    "JUMBO",
    "PRIME",
    "WHALE",
    "soft shell whale",
  ],
};
